config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  resources :users, only: [] do
    resources :tweets, only: [:create]
    resources :follows, only: [:create] do
      delete :destroy, on: :collection
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'tweets/me', 'api/v1/tweets#me'
      get 'users/me', 'api/v1/users#me'
      resources :users, only: :show do
        resources :tweets, only: :index
        resources :follows, only: [:create] do
          delete :destroy, on: :collection
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  scope :from_user, -> (user) { where(user: user) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :follows, as: :follower, dependent: :destroy
  has_many :followers, as: :followable, dependent: :destroy, class_name: 'Follow'

  scope :tweets_from, -> (user) { tweets.where(user: user) }

  def follow(user)
    return if following?(user)

    follows.create!(followable: user)
  end

  def unfollow(user)
    return unless following?(user)

    follows.where(followable: user).destroy_all
  end

  def following?(user)
    follows.where(followable: user).present?
  end

  def tweets_from_follows
    Tweet.where(user_id: follows.pluck(:followable_id))
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    include Api::Response

    respond_to :json

    skip_before_action :verify_authenticity_token
    skip_before_action :authenticate_user!

    before_action :authenticate_client!

    def authenticate_client!
      return if current_user.present?

      error_response('Incorrect access token', :unauthorized, 'invalid_grant')
    end

    def current_user
      return @current_user if @current_user.present?

      return nil if basic_auth.blank?

      user = User.find_by(email: basic_auth[0])
      (@current_user = user) if user.valid_password?(basic_auth[1])
    end

    private

    # [email, password]
    def basic_auth
      @auth ||= ::Base64.decode64(request.authorization.split(' ', 2).last || '').split(/:/, 2)
    end
  end
end

app/controllers/api/response.rb
module Api::Response
  def response_with_message(status, message)
    { status: status, message: message }
  end

  def response_with_id(status, message, id)
    { status: status, message: message, id: id }
  end

  def error_response(
    message = 'Something is wrong with the parameters or the request itself',
    status = 400,
    error_category = 'Error'
  )
    render json: response_with_message(error_category || 'Error', message), status: status
  end

  def successful_response(message, status = :ok)
    render json: response_with_message('Success', message), status: status
  end

  def successful_post(id, message = 'Record Created Successfully',
                      status = 'Success')
    render json: response_with_id(status, message, id), status: :created
  end

  def successful_delete(message = 'Record Deleted Successfully')
    successful_response(message)
  end

  def unprocessable_entity(
    message = 'There is a problem with the request body you sent'
  )
    render json: response_with_message('Error', message),
           status: :unprocessable_entity
  end

  def not_found(message = 'Record not found')
    render json: response_with_message('Error', message), status: :not_found
  end
end

app/controllers/api/v1/follows_controller.rb
module Api
  module V1
    class FollowsController < Api::ApiController
      def create
        if current_user.following?(user)
          error_response 'Already following', 422
        elsif current_user.follow(user)
          successful_response 'Following now', 202
        else
          error_response 'Unable to follow', 422
        end
      end

      # Unfollow
      def destroy
        if current_user.unfollow(user)
          successful_response 'Unfollowing now', 200
        else
          error_response 'Unable to unfollow', 422
        end
      end

      private
        def user
          @follow_user ||= User.find_by(id: params[:user_id])
        end
    end
  end
end

app/controllers/api/v1/tweets_controller.rb
module Api
  module V1
    class TweetsController < Api::ApiController
      def me
        @tweets = current_user.tweets_from_follows
        @tweets = @tweets.order(created_at: ((params[:sort] == 'asc') ? :asc : :desc))
        render json: @tweets
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::ApiController
      def me
        render json: current_user
      end

      def show
        user = User.find_by(id: params[:id])
        render json: user
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @tweets = current_user.tweets_from_follows
    @users = User.all.where.not(id: current_user.id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # Follow
  def create
    if current_user.following?(user)
      redirect_to root_path, alert: 'Already following', status: 422
    elsif current_user.follow(user)
      redirect_to root_path, alert: 'Following now', status: 202
    else
      redirect_to root_path, alert: 'Unable to follow', status: 422
    end
  end

  # Unfollow
  def destroy
    if current_user.unfollow(user)
      redirect_to root_path, alert: 'Unfollowing now', status: 200
    else
      redirect_to root_path, alert: 'Unable to unfollow', status: 422
    end
  end

  private
    def user
      @follow_user ||= User.find_by(id: params[:user_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    @tweet = current_user.tweets.new(tweet_params)
    @tweet.save
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<%= render 'shared/messages' %>

<h1>Me:</h1>
<p>User: <%= current_user.email %></p>

<%= render 'tweets/new' %>

<hr />

<div class='users'>
  <h1>Users:</h1>
  <% @users.each do |user| %>
    <%= render partial: 'users/user', locals: { user: user } %>
  <% end %>
</div>

<hr />

<div class='tweets'>
  <h1>Tweets:</h1>
  <% @tweets.each do |tweet| %>
    <%= render partial: 'tweets/tweet', locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignmentTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>
<% if flash.present? %>
  <hr />
<% end %>

app/views/tweets/_new.html.erb
<%= form_for current_user.tweets.new, method: :post, url: user_tweets_path(current_user) do |f| %>
  Tweet: <%= f.text_area :content %><br />
  <%= f.submit %>
<% end %>

app/views/tweets/_tweet.html.erb
<% if tweet.persisted? %>
  <div class="tweet">
    <p>User: <%= tweet.user.email %></p>
    <p>Tweeted: <%= tweet.content %></p>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if user.present? %>
  <div class="user">
    <p>User: <%= user.email %></p>
    <% unless current_user.following?(user) %>
      <%= link_to 'Follow', user_follows_path(user_id: user.id), method: :post %>
    <% else %>
      <%= link_to 'Unfollow', user_follows_path(user_id: user.id), method: :delete %>
    <% end %>
  </div>
<% end %>